export const SET_SHIPPING_DETAIL ='SET_SHIPPING_DETAIL'
//export const SET_RECEIVER_ADDRESS = 'SET_RECEIVER_ADDRESS'
//export const SET_WEIGHT = 'SET_WEIGHT'
//export const SET_SHIPPING_OPTION ='SET_SHIPPING_OPTION'
export const SET_STEPS ='SET_STEPS'
export const RECEIVER_HEADER ='Please Enter Receiver details here'
export const LOGIN_HEADER ='LOGIN'
export const SENDER_HEADER ='Please Enter sender details here'
export const PRODUCT_DETAILS ='Please Enter product details here'
export const SUCCESS_HEADER ='ORDER SUCCESSFUL'
export const API_URL ='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7upLt1XbQBH3XYtFyr5i2JVd9he_dRmyHOI5G6VR20-jdvNd0Vg'
export const TRY_AGAIN ='Wrong Credentials. Please try again!'
export const COPY_RIGHT = 'Copyright © 2014-2017 UNDERSTOOD.ORG USA LLC. All rights reserved. “Understood” and related logos are trademarks of UNDERSTOOD.ORG'

